Update to Roster.java
cs234-24s-group1/womens-basketball-stats pull request #17
Opened 2024-03-04 17:46 UTC by mecberry

2024-03-04 20:03 UTC, jpappel requested changes
the `.idea` files are files for your IDE and should not be committed to the repo, I will update the `.gitignore` to properly reflect this

additionally, instead of a `getRoster` method we need a `getPlayer` method to abstract the internal details of our implementation

2024-03-04 20:30 UTC, jpappel approved these changes

2024-03-04 20:32 UTC, jpappel commented
I believe this is now in the needed state for both the front end and database teams

2024-03-05 00:57 UTC, tnelson3606 approved these changes

2024-03-05 01:42 UTC, merged

2024-03-05 03:49 UTC, ZingBing reviewed
Looks awesome to me